# Numpy crash course


In [3]:
import numpy as np

In [4]:
np.__version__

'2.2.4'

In [5]:
import sys 
sys.version

'3.13.3 (main, Apr  8 2025, 13:54:08) [Clang 16.0.0 (clang-1600.0.26.6)]'

# Create an array


In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [12]:
type(my_list)

list

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(20,10) #  1st arg must b3 < 2nd arg

array([], dtype=int64)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
ar = np.arange(-30,20)

In [22]:
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [23]:
np.arange(-30,20,5)# 5 is step count 

array([-30, -25, -20, -15, -10,  -5,   0,   5,  10,  15])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.zeros(3)# parameter tuning

array([0., 0., 0.])

In [26]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
zero = np.zeros((2,4),dtype=int)
print(zero)
print(type(zero))

[[0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>


In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((10,30),dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [33]:
np.zeros((5,10),dtype=int)# bydefault first arg is row and 2nd arg is column

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [38]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
np.twos(2,3)

AttributeError: module 'numpy' has no attribute 'twos'

In [41]:
np.threes(34)

AttributeError: module 'numpy' has no attribute 'threes'

In [42]:
r = range(5)

In [43]:
r

range(0, 5)

In [45]:
for i in r:
  print(i)

0
1
2
3
4


In [ ]:
list(range(1,10,3))

[1, 4, 7]

In [47]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [48]:
np.random.rand(5)

array([0.16175696, 0.17669499, 0.47863025, 0.37810306, 0.74641986])

In [49]:
np.random.randint(2,4)

2

In [50]:
np.random.randint(10,20,5)

array([16, 10, 14, 10, 15])

In [51]:
np.random.randint(1,6,4)

array([1, 3, 5, 3])

In [53]:
np.random.rand(3)

array([0.14785286, 0.12799085, 0.66726491])

In [54]:
np.random.randint(-30,20,10) 

array([-12,  11,  14,   0,   6,   2,  -5, -22,   0,   3])

In [55]:
np.random.randint(10,40,(10,10)) #generate 10*10 matrix with random values between 10 and 40

array([[19, 36, 21, 12, 25, 39, 39, 28, 26, 20],
       [26, 32, 18, 20, 30, 10, 25, 11, 10, 23],
       [20, 29, 21, 34, 21, 36, 21, 36, 37, 14],
       [28, 11, 10, 34, 16, 21, 28, 21, 30, 34],
       [23, 26, 38, 33, 37, 37, 13, 20, 36, 32],
       [26, 28, 21, 11, 23, 22, 33, 31, 12, 26],
       [25, 23, 32, 20, 22, 24, 15, 23, 39, 15],
       [10, 26, 28, 38, 16, 34, 18, 37, 12, 28],
       [33, 13, 23, 20, 11, 34, 25, 29, 11, 10],
       [10, 36, 12, 12, 38, 32, 27, 16, 18, 29]])

In [56]:
np.random.randint(1,100,(12,12)) #generate 12*12 matrix with random values between 1 and 100

array([[61, 26, 41, 32, 52, 39, 53, 69, 95,  4,  2, 61],
       [59, 63, 15, 40, 90,  9, 20, 79, 90, 93, 23, 81],
       [78, 17,  9, 84, 44, 10, 17,  5, 21, 14, 12, 31],
       [ 6, 30, 72,  4, 41, 10, 81, 31, 81, 87, 34, 64],
       [49, 88, 30, 52, 41, 34, 28,  1, 87, 61, 29, 10],
       [71, 32, 74, 63, 28, 11,  5, 15, 83, 19,  6, 56],
       [62, 69,  3, 72, 76, 96, 33, 86, 54, 51, 94, 14],
       [72, 19, 38, 56, 42, 36, 26, 84, 39, 76, 97, 81],
       [60,  1, 13, 75, 95, 56, 10, 72, 20, 65, 57, 89],
       [84, 28,  7, 54, 73, 66, 72, 81, 14, 74, 37, 95],
       [97, 44,  4, 45, 25, 46, 70, 26, 19, 14, 36, 86],
       [62, 72, 91, 30, 26, 18, 88, 18, 96, 25, 84, 92]])

In [57]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [59]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 18, 12, 19],
       [11, 12, 19, 14],
       [12, 14, 11, 14],
       [15, 14, 16, 18],
       [16, 10, 16, 18]])

In [60]:
type(b)

numpy.ndarray

In [61]:
b

array([[14, 18, 12, 19],
       [11, 12, 19, 14],
       [12, 14, 11, 14],
       [15, 14, 16, 18],
       [16, 10, 16, 18]])

In [62]:
b[:]

array([[14, 18, 12, 19],
       [11, 12, 19, 14],
       [12, 14, 11, 14],
       [15, 14, 16, 18],
       [16, 10, 16, 18]])

In [64]:
b[3,2]

np.int64(16)

In [65]:
b[1,3]

np.int64(14)

In [66]:
b[1,-1]

np.int64(14)

In [67]:
b[2:3]

array([[12, 14, 11, 14]])

In [68]:
b[0:-2]

array([[14, 18, 12, 19],
       [11, 12, 19, 14],
       [12, 14, 11, 14]])

In [70]:
b

array([[14, 18, 12, 19],
       [11, 12, 19, 14],
       [12, 14, 11, 14],
       [15, 14, 16, 18],
       [16, 10, 16, 18]])

In [69]:
b [-5,-3]

np.int64(18)

In [71]:
b[-4,2]

np.int64(19)

In [72]:
np.random.randint(10,20,(4,4))

array([[18, 15, 13, 10],
       [13, 15, 15, 17],
       [13, 11, 14, 14],
       [11, 15, 12, 15]])

In [73]:
b[-4,-2]

np.int64(19)

# operations


In [75]:
a= np.random.randint(10,20,10)
a

array([10, 10, 10, 19, 11, 18, 14, 14, 19, 11])

In [77]:
id(a)

4400414032

In [78]:
arr

array([0, 1, 2, 3, 4, 5])

In [79]:
arr2 = np.random.randint(0,100,(10,10))

In [80]:
arr2

array([[19, 46,  9, 67, 68, 10, 54, 46, 90, 56],
       [18, 62, 77, 76, 83, 87, 88, 30, 70, 91],
       [10, 62, 87, 99, 90, 90,  2, 60, 19, 24],
       [49, 42, 27, 79,  7, 58, 89, 48, 47,  1],
       [90,  7, 58, 46, 43, 10, 87, 85, 42, 36],
       [81, 98, 21, 24, 50, 31, 56, 16, 43, 44],
       [ 9, 45, 58, 38, 75, 75, 23,  4, 77,  2],
       [65, 90, 44, 21, 92, 61, 20, 40,  8, 84],
       [30, 22, 17, 14, 32, 18, 95, 21, 65,  1],
       [ 2, 60, 21, 85, 68, 10, 40, 92, 47, 22]])

In [81]:
arr2[-5,5] 

np.int64(31)

In [82]:
arr2[-1,-2]

np.int64(47)

In [84]:
arr2[::-1]# prints in reverse 

array([[ 2, 60, 21, 85, 68, 10, 40, 92, 47, 22],
       [30, 22, 17, 14, 32, 18, 95, 21, 65,  1],
       [65, 90, 44, 21, 92, 61, 20, 40,  8, 84],
       [ 9, 45, 58, 38, 75, 75, 23,  4, 77,  2],
       [81, 98, 21, 24, 50, 31, 56, 16, 43, 44],
       [90,  7, 58, 46, 43, 10, 87, 85, 42, 36],
       [49, 42, 27, 79,  7, 58, 89, 48, 47,  1],
       [10, 62, 87, 99, 90, 90,  2, 60, 19, 24],
       [18, 62, 77, 76, 83, 87, 88, 30, 70, 91],
       [19, 46,  9, 67, 68, 10, 54, 46, 90, 56]])

In [85]:
arr2[::-2] 

array([[ 2, 60, 21, 85, 68, 10, 40, 92, 47, 22],
       [65, 90, 44, 21, 92, 61, 20, 40,  8, 84],
       [81, 98, 21, 24, 50, 31, 56, 16, 43, 44],
       [49, 42, 27, 79,  7, 58, 89, 48, 47,  1],
       [18, 62, 77, 76, 83, 87, 88, 30, 70, 91]])

In [86]:
arr2[::-3]

array([[ 2, 60, 21, 85, 68, 10, 40, 92, 47, 22],
       [ 9, 45, 58, 38, 75, 75, 23,  4, 77,  2],
       [49, 42, 27, 79,  7, 58, 89, 48, 47,  1],
       [19, 46,  9, 67, 68, 10, 54, 46, 90, 56]])

In [87]:
arr.max()

np.int64(5)

In [88]:
arr.min()

np.int64(0)

In [89]:
arr.mean()

np.float64(2.5)

In [90]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [91]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [92]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [93]:
arr

array([0, 1, 2, 3, 4, 5])

In [95]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [97]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
arr.reshape(2,3,order='C') # C means row wise

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
arr.reshape(2,3,order='F') # print element with column wise

array([[0, 2, 4],
       [1, 3, 5]])

In [101]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [104]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [105]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [106]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [107]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [108]:
mat = np.arange(0,100).reshape(10,10) 

In [109]:
row = 4
col = 5

In [110]:
mat [row,col] # 4th row and 5th column

np.int64(45)

In [111]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
col= 6

In [113]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [115]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [117]:
row

4

In [118]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [119]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [120]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [121]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [122]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [123]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [127]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [128]:
mat[1,4]

np.int64(14)

In [129]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [130]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [131]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [133]:
mat[5:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [134]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [135]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [136]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [138]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [139]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [140]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [141]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat[2:6,2:4] #2:6 → Select rows from index 2 to 5 (remember: the end index is exclusive, so it doesn't include 6)
#2:4 → Select columns from index 2 to 3 (same rule: doesn’t include 4)

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [145]:
mat[3,5]

np.int64(35)

In [146]:
mat[2:4,2:5]

array([[22, 23, 24],
       [32, 33, 34]])

In [147]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [148]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
mat[2:3,4:5]

array([[24]])

# Masking


In [150]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
id(mat)

4408074544

In [152]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [153]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [154]:
ma >50

TypeError: '>' not supported between instances of 'module' and 'int'

In [155]:
mat[mat==50]

array([50])

In [157]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [159]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [162]:
a3 = mat[mat==50]
a3

array([50])

In [163]:
a4 = mat[mat<=50]
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Python program to generate an otp


In [176]:
import random
def generate_otp(length=6):
  """Generate an otp of optimal length"""
  digits = "0123456789"
  otp = ''.join(random.choice(digits) for _ in range(length))
  return otp

# Example usage# You can change this to any length you prefer
otp_length = 6
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 482016
